language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - sshpass

after_success:
  - export SSHPASS=$PASS
  - test "$TRAVIS_TAG" = "" && export PATH=$DEV_PATH
  - test "$TRAVIS_TAG" != "" && export PATH=$PROD_PATH
  - sshpass -e scp -o stricthostkeychecking=no target/todo-spark.jar $USER@$HOST:$PATH

#after_success:
#  - bash deploy.sh

#deploy:
#  - provider: script
#    script: deploy.sh