language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - sshpass

after_success:
  - bash deploy.sh

#deploy:
#  - provider: script
#    script: deploy.sh
#    on:
#      tags: false
#  - provider: script
#    script: deploy_prod.sh
#    on:
#      tags: true