language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - sshpass

deploy:
  - provider: script
    script: deploy_dev.sh
    on:
      tags: false
  - provider: script
    script: deploy_prod.sh
    on:
      tags: true