language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - sshpass

after_success:
  - export SSHPASS=$PASS
  - sshpass -e scp -o stricthostkeychecking=no target/todo-spark.jar $USER@$HOST:$DEV_PATH

#after_success:
#  - bash deploy.sh

#deploy:
#  - provider: script
#    script: deploy.sh