language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - sshpass

after_success:
  - if [[ $TRAVIS_TAG == "" ]]; then echo "DEV"; fi
  - if [[ $TRAVIS_TAG != "" ]]; then echo "TAG"; fi