language: java
jdk:
  - oraclejdk8

addons:
  ssh_known_hosts: $HOST
  apt:
    packages:
      - sshpass

after_success:
  - export SSHPASS=$PASS
  - if [[ "$TRAVIS_TAG" == "" ]]; then export PATH=$DEV_PATH; else export PATH=$PROD_PATH fi;
  - sshpass -e scp -o target/todo-spark.jar $USER@$HOST:$PATH

#after_success:
#  - bash deploy.sh

#deploy:
#  - provider: script
#    script: deploy.sh