language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - sshpass

after_success:
  - export SSHPASS=$PASS
  - if [[ "$TRAVIS_TAG" == "" ]] ;
    then export PATH=$DEV_PATH ;
    else export PATH=$PROD_PATH ;
    fi
  - sshpass -e scp -o stricthostkeychecking=no target/todo-spark.jar $USER@$HOST:$PATH

#after_success:
#  - bash deploy.sh

#deploy:
#  - provider: script
#    script: deploy.sh